import React from "react";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App About Page',
  description: 'Generated by create next app - This is about page...',
}

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <div className="flex justify-center items-center h-screen">{children}</div>
}
